# mdsret001
# OS 2: Build propane molecule
# Due: 15 June 2021

#variables
JC = javac
JV = java


clean:
	$(RM) molecule/*.class

run:
	$(JV) molecule.RunSimulation 24 9

default: 
	$(JC) molecule/*.java 